### ISSUE TITLE
Missing jaxb package and related classes/source files.

### ISSUE THREAD

**Issue by moonrockfamily** [farnetto/log4jconverter#1]
Information:java: Errors occurred while compiling module 'log4jconverter'
Information:javac 1.8.0_171 was used to compile java sources
Information:Module "log4jconverter" was fully rebuilt due to project configuration/dependencies changes
Information:7/26/2018 1:49 PM - Compilation completed with 3 errors and 0 warnings in 2 s 55 ms
C:\Users\thiles\IdeaProjects\log4jconverter\src\main\java\farnetto\log4jconverter\Converter.java
    Error:Error:line (33)java: package farnetto.log4jconverter.jaxb does not exist
    Error:Error:line (111)java: cannot find symbol
  symbol:   class Log4JConfiguration
  location: class farnetto.log4jconverter.Converter
    Error:Error:line (125)java: cannot find symbol
  symbol:   class Log4JConfiguration
  location: class farnetto.log4jconverter.Converter

**Comment by farnetto** [comment]
Log4jConfiguration (and other classes in the missing package) gets generated by the jaxb2-maven-plugin in the pom.xml. There might be a problem when maven calls jaxb.
How are you compiling? With maven? In an IDE? Try invoking maven on the command line.
Cheers, Stephan

**Comment by Sakethramvs** [comment]
I have the same issue, I'm trying to use IntellIj for compiling, And jaxb package is missing. Can you point me to the jar so that I can get that manually instead? I'm unable to find the  farnetto.log4jconverter.jaxb.Log4JConfiguration
 class.

**Comment by farnetto** [comment]
The class Log4jConfiguration (and several others) gets generated by JAXB from log4j.dtd (under src/main/resources/farnetto/log4jconverter/dtd, this file is taken from log4j.jar and checked in extra here, which isn't really the way to go either).
In Intellij (Community version 2018.2) I was able to generate the Java files and compile the project successfully with: right-mouse-click on project -> Maven -> Generate Sources and Update Folders.
The generated Java files are then in the folder target/generated-sources/jaxb.

**Comment by jamessevener** [comment]
I've tried to get this to build. Both from Maven command line, and in Intellij (Community version 2018.3) and I still get this same problem. That is including your tip on generating sources and update folders.

**Comment by TheGlobalist** [comment]
For whoever might come across this: I've managed to make this work by parsing the .DTD through IntelliJ's JAXB internal tool
